# $FreeBSD$

QMMP_VERSION=	1.0.1
MASTER_SITES=	http://qmmp.ylsoftware.com/files/plugins/ \
	SF/qmmp-dev/qmmp/
DISTNAME=	qmmp-${PORTVERSION}
DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo

MAINTAINER?=	liangtai.s16@gmail.com
LICENSE?=	GPLv2

USES+=		cmake:outsource pkgconfig tar:bzip2
USE_QT5+=	core gui buildtools_build
USE_LDCONFIG=	yes

PLIST_SUB+=	SHLIB_VER=${PORTVERSION:C/-.*//}

pre-configure:
	@${RM} -f ${BUILD_WRKSRC}/CMakeCache.txt
