# $FreeBSD$

PORTNAME=	qmmp-plugin-stereo
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Stereo effect plug-in of QMMP (Qt4)

LICENSE=	GPLv2

QMMPPLUGIN_TARGET=	Effect/stereo
QMMPPLUGIN_OPTIONS=

.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
.include <bsd.port.mk>
