# $FreeBSD$

PORTNAME=	qmmp-plugin-stereo
CATEGORIES=	audio multimedia

COMMENT=	stereo effect plug-in of QMMP

QMMPPLUGIN_TARGET=	Effect/stereo
QMMPPLUGIN_TAG=	STEREO

DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo
.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
