# $FreeBSD$

PORTNAME=	qmmp-qt4-plugin-oss
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	OSS output plug-in of QMMP (Qt4)

LICENSE=	GPLv2

QMMPPLUGIN_TARGET=	Output/oss
QMMPPLUGIN_OPTIONS=	OSS_PLUGIN

.include "${.CURDIR}/../../multimedia/qmmp-qt4/Makefile.plugin"
.include <bsd.port.mk>
