# $FreeBSD$

PORTNAME=	qmmp-plugin-gnomehotkey
CATEGORIES=	accessibility multimedia

COMMENT=	GNOME/Cinnamon shortcut key plug-in of QMMP

USE_QT4+=	dbus network xml
LIB_DEPENDS+=	libqmmpui.so:${PORTSDIR}/multimedia/qmmp-uilib

QMMPPLUGIN_TARGET=	General/gnomehotkey
QMMPPLUGIN_OPTIONS=

DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo
.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
