# $FreeBSD$

PORTNAME=	qmmp-plugin-srconv
CATEGORIES=	audio multimedia

COMMENT=	sample rate converter dsp-effect plug-in of QMMP

QMMPPLUGIN_TARGET=	Effect/srconverter
QMMPPLUGIN_OPTIONS=

DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo
.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
