# $FreeBSD$

PORTNAME=	qmmp-qt5-plugin-nullout
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Null output plug-in of QMMP (Qt5)

LICENSE=	GPLv2

QMMPPLUGIN_TARGET=	Output/null
QMMPPLUGIN_TAG=	NULL

.include "${.CURDIR}/../../multimedia/qmmp-qt5/Makefile.plugin"
.include <bsd.port.mk>
