# $FreeBSD$

PORTNAME=	qmmp-qt4-plugin-stereo
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Stereo effect plug-in of QMMP (Qt4)

LICENSE=	GPLv2

QMMPPLUGIN_TARGET=	Effect/stereo
QMMPPLUGIN_TAG=	STEREO

.include "${.CURDIR}/../../multimedia/qmmp-qt4/Makefile.plugin"
.include <bsd.port.mk>
