# $FreeBSD$

PORTNAME=	qmmp-qt5-plugin-crossfade
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Crossfade dsp-effect plug-in of QMMP (Qt5)

LICENSE=	GPLv2

QMMPPLUGIN_TARGET=	Effect/crossfade
QMMPPLUGIN_OPTIONS=

.include "${.CURDIR}/../../multimedia/qmmp-qt5/Makefile.plugin"
.include <bsd.port.mk>
