# $FreeBSD$

PORTNAME=	qmmp-plugin-analyzer
CATEGORIES=	multimedia

COMMENT=	spectrum analyzer visualization plug-in of QMMP

QMMPPLUGIN_TARGET=	Visual/analyzer
QMMPPLUGIN_TAG=	ANALYZER

DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo
.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
