# $FreeBSD$

PORTNAME=	qmmp-plugin-crossfade
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Crossfade dsp-effect plug-in of QMMP (Qt4)

LICENSE=	GPLv2

USE_QT+=	uic_build

QMMPPLUGIN_TARGET=	Effect/crossfade
QMMPPLUGIN_TAG=	CROSSFADE

.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
.include <bsd.port.mk>
