# $FreeBSD$

PORTNAME=	qmmp-plugin-crossfade
CATEGORIES=	audio multimedia

COMMENT=	crossfade dsp-effect plug-in of QMMP

QMMPPLUGIN_TARGET=	Effect/crossfade
QMMPPLUGIN_OPTIONS=

DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo
.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
