# $FreeBSD$

PORTNAME=	qmmp-plugin-nullout
CATEGORIES=	audio multimedia

COMMENT=	null output plug-in of QMMP

QMMPPLUGIN_TARGET=	Output/null
QMMPPLUGIN_OPTIONS=

DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo
.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
