# $FreeBSD$

PORTNAME=	libsidplayfp
PORTVERSION=	1.2.1
CATEGORIES=	audio
MASTER_SITES=	SF/sidplay-residfp/libsidplayfp/1.2

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Library to play Commodore 64 music derived from libsidplay2

USES=		pathfix pkgconfig gmake
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
