# $FreeBSD$

PORTNAME=	libsidplayfp
PORTVERSION=	1.4.2
CATEGORIES=	audio
MASTER_SITES=	SF/sidplay-residfp/libsidplayfp/${PORTVERSION:R}

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Library to play Commodore 64 music derived from libsidplay2

USES=		pathfix pkgconfig gmake libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

SIDPLAYFP_SHLIB_MVER=	3
SIDPLAYFP_SHLIB_VER=	${SIDPLAYFP_SHLIB_MVER}.0.11
STILVIEW_SHLIB_MVER=	0
STILVIEW_SHLIB_VER=	${STILVIEW_SHLIB_MVER}.0.1

.include <bsd.port.mk>
