# $FreeBSD$

PORTNAME=	qmmp-plugin-oss
CATEGORIES=	audio multimedia

COMMENT=	oss output plug-in of QMMP

QMMPPLUGIN_TARGET=	Output/oss
QMMPPLUGIN_OPTIONS=	OSS_PLUGIN

DISTINFO_FILE=	${.CURDIR}/../../multimedia/qmmp/distinfo
.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
