# $FreeBSD$

PORTNAME=	qmmp-plugin-oss
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	OSS output plug-in of QMMP (Qt4)

LICENSE=	GPLv2

USE_QT4+=	uic_build

QMMPPLUGIN_TARGET=	Output/oss
QMMPPLUGIN_TAG=	OSS

.include "${.CURDIR}/../../multimedia/qmmp/Makefile.plugin"
.include <bsd.port.mk>
