# $FreeBSD$

PORTNAME=	qmmp-qt5-plugin-analyzer
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Spectrum analyzer visualization plug-in of QMMP (Qt5)

LICENSE=	GPLv2

QMMPPLUGIN_TARGET=	Visual/analyzer
QMMPPLUGIN_OPTIONS=

.include "${.CURDIR}/../../multimedia/qmmp-qt5/Makefile.plugin"
.include <bsd.port.mk>
