# $FreeBSD$

PORTNAME=	qmmp-qt4-plugin-srconv
PORTVERSION=	${QMMP_VERSION}
CATEGORIES=	audio multimedia

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	Sample rate converter dsp-effect plug-in of QMMP (Qt4)

LICENSE=	GPLv2

QMMPPLUGIN_TARGET=	Effect/srconverter
QMMPPLUGIN_OPTIONS=

.include "${.CURDIR}/../../multimedia/qmmp-qt4/Makefile.plugin"
.include <bsd.port.mk>
